name: test1
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  
  flutter_inappwebview: ^6.0.0 
  firebase_auth: ^5.1.0
  cloud_firestore:
  get: ^4.6.5
  firebase_core: ^3.1.0
  google_mobile_ads:
  video_player: ^2.8.0
  http: ^1.4.0
  chewie: ^1.4.0
  shared_preferences: ^2.2.3
  get_it: ^8.1.0
  flutter:
    sdk: flutter

  onesignal_flutter: ^5.3.4
  cupertino_icons: ^1.0.8
  firebase_remote_config: ^5.0.1
  firebase_analytics: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0




flutter:

  generate: true

  
  uses-material-design: true

  
  assets:
   - assets/images/profile.jpg
  
   
   

 
